### ISSUE TITLE
Make looks more like "blog" less like page?

### ISSUE THREAD

**Issue by ktoso** [ktoso/let-it-crash#1]
![let_it_crash__ _the_akka_team_blog___akka_team_blog](https://cloud.githubusercontent.com/assets/120979/16250207/d3318d96-381b-11e6-9a2c-ba5103038f2b.png)

**Comment by ktoso** [comment]
![happy_hakking____akka_team_blog](https://cloud.githubusercontent.com/assets/120979/16250181/97153eca-381b-11e6-992c-e832403e4c14.png)

**Comment by ktoso** [comment]
FYI @drewhk @2m @patriknw 

Just needs:
- some minor tweaks (looks a bit crappy in places),
- adding the Disqus code
- google analytics should just work
- switching letitcrash.com domain or blog.akka.io?

**Comment by 2m** [comment]
The more narrow layout looks really good.

**Comment by ktoso** [comment]
It's directly stolen from our news site :-)
Was thinking that maybe too similar hm...

**Comment by patriknw** [comment]
good
